package br.com.sisgete.view;

import static br.com.sisgete.view.MenuOpcoesView.RET_OK;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author luiz
 */
public class MenuObservacaoView extends javax.swing.JDialog {

    public int dias = 0;
    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form MenuObservacaoView
     *
     * @param parent
     * @param modal
     */
    public MenuObservacaoView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jb30Dias = new javax.swing.JButton();
        jb60Dias = new javax.swing.JButton();
        jb90Dias = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel1.setText("SELECIONE A QUANTIDADE DE DIAS DE OBSERVAÇÃO");

        jb30Dias.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jb30Dias.setText("30");
        jb30Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb30DiasActionPerformed(evt);
            }
        });

        jb60Dias.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jb60Dias.setText("60");
        jb60Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb60DiasActionPerformed(evt);
            }
        });

        jb90Dias.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jb90Dias.setText("90");
        jb90Dias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb90DiasActionPerformed(evt);
            }
        });

        jbCancelar.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jb30Dias)
                        .addGap(39, 39, 39)
                        .addComponent(jb60Dias)
                        .addGap(30, 30, 30)
                        .addComponent(jb90Dias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbCancelar)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb30Dias)
                    .addComponent(jb60Dias)
                    .addComponent(jb90Dias)
                    .addComponent(jbCancelar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jb30DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb30DiasActionPerformed
        doClose(RET_OK);
        dias = 30;
    }//GEN-LAST:event_jb30DiasActionPerformed

    private void jb60DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb60DiasActionPerformed
        doClose(RET_OK);
        dias = 60;
    }//GEN-LAST:event_jb60DiasActionPerformed

    private void jb90DiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb90DiasActionPerformed
        doClose(RET_OK);
        dias = 90;
    }//GEN-LAST:event_jb90DiasActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jb30Dias;
    private javax.swing.JButton jb60Dias;
    private javax.swing.JButton jb90Dias;
    private javax.swing.JButton jbCancelar;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
